application: GOOGLE-COMPUTE_PROJCT-ID 
version: 1

runtime: python27
api_version: 1
threadsafe: yes

handlers:
  - url: /(.+)
    static_files: public/\1
    upload: public/(.*)

  - url: /
    static_files: public/index.html
    upload: public/index.html

skip_files:
- ^test$
- .git$
- .*git.*

# https://gist.github.com/darktable/873098
# http://www.fizerkhan.com/blog/posts/Free-Static-Page-Hosting-on-Google-App-Engine-in-a-5-minutes.html
